name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.BUDGETPIE_HOST_SSH_IP}} # IP address of the server you wish to ssh into
          key: ${{secrets.BUDGETPIE_SSH_PRIVATE_KEY}} # Private or public key of the server
          username: ${{ secrets.BUDGETPIE_HOST_SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            mkdir -p test 
            cd test 
            git clone https://github.com/ghazanfarali345/Node-Rest-API-CRUD.git 
            echo 'Deployment successful to Digital Ocean'
